const router = require('express').Router();
const auth = require('../middleware/auth');
const authController = require('../controllers/authController');
const tripController = require('../controllers/tripController');
const discoveryController = require('../controllers/discoveryController');
const alertController = require('../controllers/alertController');
const optionalAuth = require('../middleware/optionalAuth');
const searchRateLimit = require('../middleware/searchRateLimit');
router.post('/auth/register', authController.register);
router.post('/auth/login', authController.login);
router.get('/auth/me', auth, authController.me);
router.put('/users/preferences', auth, authController.preferences);
router.get('/airports', discoveryController.airports);
router.get('/destinations', discoveryController.destinations);
router.get('/destinations/:id', discoveryController.destination);
router.get('/deals', discoveryController.deals);
router.get('/prices/:origin/:destination', discoveryController.routePrices);
router.get('/places', discoveryController.places);
router.get('/weather', discoveryController.weather);
router.get('/nearby-airports', discoveryController.nearbyAirports);
router.post('/search', optionalAuth, searchRateLimit, discoveryController.search);
router.post('/booking/click', optionalAuth, discoveryController.bookingClick);
router.get('/trips', auth, tripController.list);
router.post('/trips', auth, tripController.create);
router.get('/trips/:id', auth, tripController.get);
router.put('/trips/:id', auth, tripController.update);
router.delete('/trips/:id', auth, tripController.remove);
router.get('/trips/:id/itinerary', auth, tripController.getItinerary);
router.put('/trips/:id/itinerary', auth, tripController.itinerary);
router.post('/trips/:id/optimize', auth, tripController.optimize);
router.get('/alerts', auth, alertController.list);
router.post('/alerts', auth, alertController.create);
router.put('/alerts/:id', auth, alertController.update);
router.delete('/alerts/:id', auth, alertController.remove);
router.post('/alerts/:id/refresh', auth, alertController.refresh);
module.exports = router;
