import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import api from '../api'
const destinations = ['Anywhere', 'New York', 'London', 'Paris', 'Tokyo', 'Dubai', 'Singapore', 'Bali', 'Rome']
export default function Search() {
  const [form, setForm] = useState({ origin: '', destination: 'Anywhere', departureDate: '', returnDate: '', travelers: 1, budget: '', currency: 'USD', preferences: { travelStyle: 'balanced' } }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate()
  const change = (key, value) => setForm({ ...form, [key]: value })
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post('/search', form); navigate('/results', { state: { opportunities: data.opportunities, search: form } }) } catch (err) { setError(err.response?.data?.error || 'We could not find trips right now.') } finally { setBusy(false) } }
  return <section className="page"><div className="page-heading"><span className="eyebrow">DISCOVER YOUR NEXT ESCAPE</span><h1>Where could you go?</h1><p>Give us the constraints. We’ll show you the complete picture.</p></div><form className="search-form" onSubmit={submit}><div className="form-row"><label>Flying from<input required value={form.origin} onChange={e => change('origin', e.target.value)} placeholder="Airport code (e.g. JFK)" /></label><label>Destination<select value={form.destination} onChange={e => change('destination', e.target.value)}>{destinations.map(d => <option key={d}>{d}</option>)}</select></label></div><div className="form-row"><label>Departure<input required type="date" value={form.departureDate} onChange={e => change('departureDate', e.target.value)} /></label><label>Return<input required type="date" value={form.returnDate} onChange={e => change('returnDate', e.target.value)} /></label><label>Travelers<input required min="1" type="number" value={form.travelers} onChange={e => change('travelers', e.target.value)} /></label></div><div className="form-row"><label>Budget per trip<input type="number" min="0" value={form.budget} onChange={e => change('budget', e.target.value)} placeholder="Optional" /></label><label>Currency<select value={form.currency} onChange={e => change('currency', e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option><option>INR</option></select></label><label>Travel style<select value={form.preferences.travelStyle} onChange={e => setForm({ ...form, preferences: { ...form.preferences, travelStyle: e.target.value } })}><option value="balanced">Balanced</option><option value="budget">Budget smart</option><option value="comfort">Comfort</option></select></label></div>{error && <div className="error">{error}</div>}<button className="button" disabled={busy}>{busy ? 'Finding your options…' : 'Find my trips →'}</button></form><div className="source-note">✦ Flight and hotel availability is live where supported. Food, transport and activities are clearly marked estimates.</div></section>
}
